language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - pandoc
install:
  - pip install .
  - pip install -r tests/requirements.txt
  - pip install -r doc/requirements.txt
script:
  - python -m pytest
  # This executes the example notebooks:
  - python -m sphinx doc/ _build/ -b dummy
